# Netlify configuration file

# Build settings
[build]
<<<<<<< HEAD
  base = "client"
  publish = "dist"
  command = "npm run build"
=======
  publish = "dist"
  command = "npm run netlify-build"
>>>>>>> b1a8bb87a9f2e1b3c2ce0c8518a40cf83a513f40

# SPA redirect rule - All routes should be handled by index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

<<<<<<< HEAD
# Note: Headers are defined in the _headers file
# This approach avoids duplication and makes maintenance easier
=======
# Headers to ensure proper MIME types for JavaScript modules
[[headers]]
  for = "/assets/*.js"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"

[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"

[[headers]]
  for = "/assets/*.mjs"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"

[[headers]]
  for = "/*.mjs"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"

[[headers]]
  for = "/assets/*.css"
  [headers.values]
    Content-Type = "text/css; charset=utf-8"

[[headers]]
  for = "/*.css"
  [headers.values]
    Content-Type = "text/css; charset=utf-8"

# Cache control for static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
>>>>>>> b1a8bb87a9f2e1b3c2ce0c8518a40cf83a513f40
