# Netlify configuration file

# Build settings
[build]
  base = "client"
  publish = "dist"
  command = "npm run build"

# SPA redirect rule - All routes should be handled by index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Note: Headers are defined in the _headers file
# This approach avoids duplication and makes maintenance easier
