services:
  - type: web
    name: tradebro-server
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: SESSION_SECRET
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: FMP_API_KEY
        sync: false
      - key: TWELVE_DATA_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: PUSHER_APP_ID
        sync: false
      - key: PUSHER_KEY
        sync: false
      - key: PUSHER_SECRET
        sync: false
      - key: PUSHER_CLUSTER
        sync: false
      - key: EMAIL_SERVICE
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASSWORD
        sync: false
      - key: email_nodemailer
        sync: false
      - key: password_nodemailer
        sync: false
      - key: CLIENT_URL
        value: https://tradebro.netlify.app
      - key: API_BASE_URL
        value: https://s89-satya-capstone-tradebro.onrender.com
